FROM node:16-alpine

WORKDIR /usr/src/api-gateway

COPY package*.json ./

RUN npm install

COPY . .

COPY proto/auth.proto ./proto/auth.proto
COPY proto/product.proto ./proto/product.proto

EXPOSE 4000

CMD ["npm", "start"]