name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [api-gateway, auth-service, product-service, cart-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t yasimjidhu/${{ matrix.service }}:latest ./${{ matrix.service }}
          docker push yasimjidhu/${{ matrix.service }}:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull yasimjidhu/${{ matrix.service }}:latest
            docker stop ${{ matrix.service }} || true
            docker rm ${{ matrix.service }} || true
            docker run -d --name ${{ matrix.service }} -p 80:80 yasimjidhu/${{ matrix.service }}:latest
