name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push api-gateway
        uses: docker/build-push-action@v2
        with:
          context: ./services/api-gateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      - name: Build and push auth-service
        uses: docker/build-push-action@v2
        with:
          context: ./services/auth-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: Build and push product-service
        uses: docker/build-push-action@v2
        with:
          context: ./services/product-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-service:latest

      - name: Build and push cart-service
        uses: docker/build-push-action@v2
        with:
          context: ./services/cart-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cart-service:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'
      
      - name: Configure Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 --decode > $HOME/.kube/config
        
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ github.workspace }}/.kube/config
        run: |
          kubectl apply -f ./services/api-gateway/deployment.yaml --kubeconfig=$HOME/.kube/config
          kubectl apply -f ./services/auth-service/deployment.yaml --kubeconfig=$HOME/.kube/config
          kubectl apply -f ./services/product-service/deployment.yaml --kubeconfig=$HOME/.kube/config
          kubectl apply -f ./services/cart-service/deployment.yaml --kubeconfig=$HOME/.kube/config
        
